### ISSUE TITLE
testuser, testuser2 and testuser3 on production are behaving very 'weirdly'

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#121] opened 2023-09-04 10:44 UTC
We want to document specifically the weird issue around these test users

**Comment by utunga** [comment] 2023-09-04 10:46
Very likely this is related to #103

**Comment by yonasbek** [comment] 2023-09-05 05:09
There are violation class that have different meaning and out of those that might be related to this issue is MaxLimitViolation, Which is basically limiting number of pending transactions that a payee(seller or provider) can have. Because the seller couldn't pass there limit violation. And the #103 i assume is caused by this violation. So will do more testing to re generate this error and try to have more and better description.

**Comment by tfwoodroofMCS** [comment] 2023-09-05 16:03
@yonasbek I have documented #103 (and very similar #126) more thoroughly, with some suggested fixes. However these recommendations are not the result of testing via the user interface, just from looking at what the error messages say and figuring out what the intended functionality is.

**Comment by tfwoodroofMCS** [comment] 2023-09-05 16:13
To respond directly to your comment: as far as I'm aware, there's no functionality intended to limit the number of pending transactions that a user (buyer or seller) can have. However, it's an idea worth considering, so I've created #127 (in 'mañana' for now).

**Comment by tfwoodroofMCS** [comment] 2023-09-14 12:59
@yonasbek, @utunga - as far as I can recall, this issue comes down to two things: users with long transaction histories experiencing slow performance, and possible unstable behaviour at high transaction throughputs. I see this is in 'Review', but doesn't have a particular PR associated with it, or specific descriptions in the above terms - if they're accurate, perhaps it's time to create specific issues for each of these?

**Comment by yonasbek** [comment] 2023-09-14 13:38
The pr that should fix this issue is that removing the transaction from the data api and making it in its own. lets have one to one session @tfwoodroofMCS and lets try to debug it more

**Comment by utunga** [comment] 2023-09-20 11:41
Leaving this one alone for now.

However, for the record i think trying to debug 'undefined' behavior becomes an awful timesink after a while..so in my opinion I'd be ok with 
- just reset the db and start fresh removing the problem
- and closing this issue as a result

But I'll leave this one open in case you really want to do that 1-1 debugging @yonasbek

**Comment by tfwoodroofMCS** [comment] 2023-09-21 13:27
I haven't noticed an issue with heavy users experiencing slowness for a while, so this seems to have been resolved one way or another. Going to close this issue and create a new one that we should test high transaction throughputs.

**Closed by tfwoodroofMCS** 2023-09-21 13:27 UTC
